os: linux
dist: focal
language: c

install:
 - sudo apt-get update
 - sudo apt-get install --yes libgtest-dev
 - sudo apt-get install --yes gcovr

jobs:
 include:
  - stage: Build
    script:
     - cmake -B build -DCMAKE_BUILD_TYPE=Release
     - make -C build
  - stage: Test
    script:
     - cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=1
     - make -C build
     - cd build && ctest --output-on-failure
  - stage: Sanitaizer
    script:
     - cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_SANITIZERS=1
     - make -C build
     - cd build && ctest --output-on-failure
  - stage: Coverage
    script:
     - cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_COVERAGE=1
     - make -C build all test
     - curl -Os https://uploader.codecov.io/latest/linux/codecov
     - chmod +x codecov
     - ./codecov -f <(gcovr -e '.*/tests/.*' -x)